# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [1]:
import numpy

In [2]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [6]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [7]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [8]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 6.26 ms per loop


In [9]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [11]:
Z += 4

In [12]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [14]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [15]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [16]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [17]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [18]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [19]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [21]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [22]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [23]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [24]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([ 11.78220635,   8.93663103, -17.50627085, ...,  17.10257018,
         7.24243523,  -0.95099759])

## Sorting

In [25]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [26]:
print x[:10]
print x[-10:]

[ 0.00021619  0.00066141  0.0022386   0.00231872  0.00866861  0.00889664
  0.01014405  0.01216177  0.01273415  0.01466487]
[ 0.99120831  0.99250643  0.99419286  0.99490179  0.99550734  0.99653262
  0.99681669  0.99848937  0.99872478  0.99887051]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [27]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [28]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [29]:
indices[:10]

array([794,   2, 719, 257, 385, 486, 763, 772, 554, 559])

In [30]:
random_numbers.min(), random_numbers.max()

(0.0004961517756608691, 0.99889210024516806)

In [31]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(219, 0.99889210024516806)

In [32]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(794, 0.0004961517756608691)

## Exercise

In [3]:
# 0. import numpy
import numpy as np

In [15]:
# 1. sample 1000 elements from normal distribution 
random_numbers = np.random.normal(size = 1000)
print(random_numbers)

[ -4.98328627e-02   4.12287536e-01  -3.83875968e-01   3.13693025e-02
  -1.03309829e+00   1.12647751e-01   1.75768661e-01  -2.88572579e-01
  -5.59740061e-01  -1.30444286e-01   2.74835351e+00   8.60063593e-01
  -1.00361984e+00  -3.05395321e-01  -1.23408167e-02  -8.86247157e-01
  -3.77290101e-01  -3.50581960e-01   7.89401547e-01   4.33039639e-01
  -1.58713692e-01   2.23726359e+00  -1.40287687e-01   4.00166883e-01
  -2.58339661e+00  -4.29702895e-02   4.36146516e-01   3.30678877e-01
   1.48733334e+00   7.53554720e-01   4.91138083e-01  -8.06925358e-01
   6.56433930e-01  -7.36408127e-01  -1.24426903e+00  -1.17654804e+00
   4.93717134e-01  -8.83035698e-01   2.35206820e-01  -2.02261267e-01
  -2.09866849e+00   1.85690770e+00   8.70685430e-02   2.20681126e-03
   4.52058165e-01  -1.30509183e+00  -4.85473803e-01  -1.44404707e+00
  -8.97749338e-01   6.54099848e-01  -5.33103047e-01   6.36040484e-01
   1.65785444e+00   5.07588369e-01  -4.15315385e-01   3.45582743e-01
   1.75090387e-01   4.57642925e-01

In [16]:
# 2. leave only positive numbers (from previous exercise)
random_numbers = np.array([x  for x in random_numbers if x > 0])
print(random_numbers)

[  4.12287536e-01   3.13693025e-02   1.12647751e-01   1.75768661e-01
   2.74835351e+00   8.60063593e-01   7.89401547e-01   4.33039639e-01
   2.23726359e+00   4.00166883e-01   4.36146516e-01   3.30678877e-01
   1.48733334e+00   7.53554720e-01   4.91138083e-01   6.56433930e-01
   4.93717134e-01   2.35206820e-01   1.85690770e+00   8.70685430e-02
   2.20681126e-03   4.52058165e-01   6.54099848e-01   6.36040484e-01
   1.65785444e+00   5.07588369e-01   3.45582743e-01   1.75090387e-01
   4.57642925e-01   1.34957706e+00   9.99246557e-01   9.99941234e-01
   4.46150787e-01   5.89703845e-02   4.07478336e-01   3.02666479e+00
   2.85266631e-01   1.33010618e-01   9.21626796e-01   2.51314269e-01
   3.07933824e-01   8.08313991e-02   4.74777230e-01   1.29436195e+00
   2.34282932e+00   6.03557045e-01   2.26700502e+00   4.53859331e-02
   1.13276186e+00   3.05341875e-01   1.44856004e+00   1.47452647e-01
   1.10577037e+00   1.65127613e+00   4.83926442e-01   7.42731710e-01
   7.82211433e-01   9.50688396e-01

In [18]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
print(random_numbers.shape[0],random_numbers.min(),random_numbers.max(),random_numbers.mean(),random_numbers.var())

514 0.00220681125768 3.02666478887 0.798333016423 0.373335429793


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
